#pragma once

namespace input_events {
  enum class Events {
    quit,
    zero_pressed,
    one_pressed,
    two_pressed,
    three_pressed,
    four_pressed,
    five_pressed,
    six_pressed,
    seven_pressed,
    eight_pressed,
    nine_pressed,
    a_pressed,
    b_pressed,
    c_pressed,
    d_pressed,
    e_pressed,
    f_pressed,
    zero_released,
    one_released,
    two_released,
    three_released,
    four_released,
    five_released,
    six_released,
    seven_released,
    eight_released,
    nine_released,
    a_released,
    b_released,
    c_released,
    d_released,
    e_released,
    f_released,
    none,
  };
}
